### ISSUE TITLE
zzsc.exe

### ISSUE THREAD

**Issue by koko777888** [Helco/zzio#257]
Hello!

I have asked my friend to compile your code - i should launch editor using zzsc.exe no? It doesnt work for me. the version i downloaded from Releases with zzre.exe works alright.

**Comment by Helco** [comment]
My name pattern for this project did not scale well, sorry about that. zzsc is a script compiler tool, all editors/viewers are only in zzre.

**Comment by koko777888** [comment]
Thanks
