### ISSUE TITLE
3401 (Violectra Trader in Monagham): NPC displayed levitating

### ISSUE THREAD

**Issue by AcipenserSturio** [Helco/zzio#327]
Expected behaviour:

![violectra-trader-expected](https://github.com/Helco/zzio/assets/28656100/d60236cc-7c3b-4317-acb7-e6625b36a617)

Observed behaviour:

![violectra-trader-observed](https://github.com/Helco/zzio/assets/28656100/86f22b97-d695-4d17-951a-c1141a6d6310)

**Comment by Helco** [comment]
Fixed by [a622bc1](https://github.com/Helco/zzio/commit/a622bc1366726bf465f7273f078b51ea57f6c3a5)
