### ISSUE TITLE
0231 (West Tiralin): Western Gate is permanently disabled

### ISSUE THREAD

**Issue by AcipenserSturio** [Helco/zzio#328]
Expected behaviour: gate opens when player has Heavy Iron Key

Observed behaviour: gate does not open.

The opposite side of the gate (0220) works as expected.

**Comment by Helco** [comment]
The city door unlock behavior is not implemeted yet #123

**Comment by Helco** [comment]
I'll close this issue in favor of #123. The unlocking of doors, even with the unlock already stored in the savegame, is part of the unlocking behavior - which is currently missing.
